const ActionTypes = {
  START_GET_DATA: 'START_GET_DATA',
  DONE_GET_DATA: 'DONE_GET_DATA',
  MQTT_MESSAGE_ARRIVED: 'MQTT_MESSAGE_ARRIVED',
  MQTT_CONNECT: 'MQTT_CONNECT',
  MQTT_CONNECTION_SUCCESS: 'MQTT_CONNECTION_SUCCESS',
  MQTT_DISCONNECT: 'MQTT_DISCONNECT',
  MQTT_FILTER_DEVICES_NAME: 'MQTT_FILTER_DEVICES_NAME'
}

export default ActionTypes