const ActionTypes = {
  START_GET_DATA: 'START_GET_DATA',
  DONE_GET_DATA: 'DONE_GET_DATA',
  MQTT_MESSAGE_ARRIVED: 'MQTT_MESSAGE_ARRIVED',
  MQTT_CONNECT: 'MQTT_CONNECT',
  MQTT_CONNECTION_SUCCESS: 'MQTT_CONNECTION_SUCCESS',
  MQTT_DISCONNECT: 'MQTT_DISCONNECT',
  MQTT_FILTER_DEVICES_NAME: 'MQTT_FILTER_DEVICES_NAME',
  DEVICES_ONLINE: 'DEVICES_ONLINE',
  DEVICES_OFFLINE: 'DEVICES_OFFLINE',
  CHECKED_ONLINE: 'CHECKED_ONLINE',
  CHECKED_OFFLINE: 'CHECKED_OFFLINE',
  LWT: 'LWT'
}

export default ActionTypes