const ActionTypes = {
  START_GET_DATA: 'START_GET_DATA',
  DONE_GET_DATA: 'DONE_GET_DATA',
  MQTT_MESSAGE_ARRIVED: 'MQTT_MESSAGE_ARRIVED',
  MQTT_CONNECT: 'MQTT_CONNECT',
  MQTT_CONNECTION_SUCCESS: 'MQTT_CONNECTION_SUCCESS',
  MQTT_CLEAR_RETAIN: 'MQTT_CLEAR_RETAIN',
  MQTT_DISCONNECT: 'MQTT_DISCONNECT'
}

export default ActionTypes